### PR TITLE
Update stack config

### PR DESCRIPTION
**Pull request by fosskers**

### CODE REVIEW

**Comment by amosr** [comment]
Is this an automatically generated file? Should it really be in version control anyway?

**Comment by tmcdonell** [comment]
@amosr not automatically generated. It should be in VC. It's basically a more precise `.cabal` file.

Since ghc-8 isn't out of stackage nightly yet, and repa still works with both 7.10 and 8.0, perhaps we should have both a `stack-7.10.yaml` and `stack-8.0.yaml`? Otherwise I am fine with this change.

**Comment by amosr** [comment]
ok fair enough, it just looks like the same information that's already in .cabal

**Comment by fosskers** [comment]
@tmcdonell LTS-7 with GHC8 is supposed to be out some time this month.

Thanks for the merge, gents.

**Pull request merged**
